LINES=/home/jesse/TUTORIAL-HTR/EXP-RESOLUTIONS/PROC/AuxProc/Lines
LINES=/home/jesse/TUTORIAL-HTR/EXP-RESOLUTIONS/PROC/lines-png
TRANSCRIPTION=/home/jesse/TUTORIAL-HTR/EXP-RESOLUTIONS/TRAIN/tokenized-trans
RESULTS=/home/jesse/TUTORIAL-HTR/EXP-RESOLUTIONS/TEST/REC
DICTIONARY=/home/jesse/TUTORIAL-HTR/EXP-RESOLUTIONS/TRAIN/LM/INTERPOLATION/dictionary.txt
perl scripts/combineRecognitionGTAndLineImage.pl $RESULTS $TRANSCRIPTION $LINES $DICTIONARY



