LINES=/home/jesse/TUTORIAL-HTR/EXP-RESOLUTIONS/PROC/AuxProc/Lines
TRANSCRIPTION=/home/jesse/TUTORIAL-HTR/EXP-RESOLUTIONS/TRAIN/Transcriptions
RESULTS=/home/jesse/TUTORIAL-HTR/EXP-RESOLUTIONS/TEST/REC

perl scripts/combineGTAndLineImage.pl $TRANSCRIPTION $LINES



